---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grpc-server
  namespace: grpc
spec:
  chart:
    spec:
      chart: grpc-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: patricklaabs
      version: 1.0.2
  interval: 1m0s
