---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: my-restfulapi-restfulapi
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`rest.example.com`)
      kind: Rule
      services:
        - name: my-restfulapi-restfulapi
          port: 11802
