apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grpc-server
  namespace: grpc
spec:
  chart:
    spec:
      version: ">=0.1.0-alpha"
  values:
    ingress:
      hosts:
        - host: grpc.staging.com
          paths:
            - path: /
              pathType: ImplementationSpecific
